// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using SEROTECA_WEB_BACK.Models;

#nullable disable

namespace SEROTECA_WEB_BACK.Migrations
{
    [DbContext(typeof(DatabaseContext))]
    [Migration("20240921233413_InitialCreate")]
    partial class InitialCreate
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("SEROTECA_WEB_BACK.Models.OrdenPortaMuestra", b =>
                {
                    b.Property<string>("OrdenPortaMuestraId")
                        .HasMaxLength(30)
                        .HasColumnType("nvarchar(30)");

                    b.Property<string>("IdPortaMuestra")
                        .HasColumnType("nvarchar(255)");

                    b.Property<int?>("Numero")
                        .HasMaxLength(10)
                        .HasColumnType("int");

                    b.Property<int?>("PosicionColumna")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.Property<int?>("PosicionFila")
                        .HasMaxLength(2)
                        .HasColumnType("int");

                    b.HasKey("OrdenPortaMuestraId");

                    b.HasIndex("IdPortaMuestra");

                    b.ToTable("OrdenPortaMuestra");
                });

            modelBuilder.Entity("SEROTECA_WEB_BACK.Models.PortaMuestra", b =>
                {
                    b.Property<string>("IdPortaMuestra")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<int>("Columnas")
                        .HasMaxLength(255)
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasMaxLength(255)
                        .HasColumnType("nvarchar(255)");

                    b.Property<DateTime?>("FechaFin")
                        .HasMaxLength(10)
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("FechaIni")
                        .HasMaxLength(10)
                        .HasColumnType("datetime2");

                    b.Property<int?>("Filas")
                        .HasMaxLength(255)
                        .HasColumnType("int");

                    b.HasKey("IdPortaMuestra");

                    b.ToTable("PortaMuestra");
                });

            modelBuilder.Entity("SEROTECA_WEB_BACK.Models.OrdenPortaMuestra", b =>
                {
                    b.HasOne("SEROTECA_WEB_BACK.Models.PortaMuestra", "PortaMuestra")
                        .WithMany()
                        .HasForeignKey("IdPortaMuestra");

                    b.Navigation("PortaMuestra");
                });
#pragma warning restore 612, 618
        }
    }
}
